version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: description
        must_exclude:
          regex: 'Dependent-PR-not-completed'
  - when: pull_request.opened
    name: "Greet a contributor"
    validate: []
    pass:
      - do: comment
        payload:
          body: >
            Thanks for creating a pull request! A maintainer will review your changes shortly. Please don't be discouraged if it takes a while.          